"""add_kitchen_status

Revision ID: 69da4ff82cac
Revises: efcf53657847
Create Date: 2026-06-23 09:29:21.867002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69da4ff82cac'
down_revision: Union[str, None] = 'efcf53657847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('kitchen_status', sa.Enum('NEW', 'PREPARING', 'READY', 'SERVED', name='kitchenstatus', native_enum=False), nullable=False, server_default='NEW'))
    op.create_index(op.f('ix_order_items_kitchen_status'), 'order_items', ['kitchen_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_kitchen_status'), table_name='order_items')
    op.drop_column('order_items', 'kitchen_status')
    # ### end Alembic commands ###
