"""add modifiers

Revision ID: 964e1fe9cef4
Revises: 2870002bd15f
Create Date: 2026-06-27 12:57:04.553664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964e1fe9cef4'
down_revision: Union[str, None] = '2870002bd15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modifier_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('selection_type', sa.Enum('SINGLE', 'MULTIPLE', name='selectiontype', native_enum=False), nullable=False),
    sa.Column('min_select', sa.Integer(), nullable=False),
    sa.Column('max_select', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifier_groups_restaurant_id'), 'modifier_groups', ['restaurant_id'], unique=False)
    op.create_table('modifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modifier_group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modifier_group_id'], ['modifier_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifiers_modifier_group_id'), 'modifiers', ['modifier_group_id'], unique=False)
    op.create_table('menu_item_modifier_groups',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('modifier_group_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modifier_group_id'], ['modifier_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'modifier_group_id')
    )
    op.create_table('order_item_modifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('modifier_id', sa.Uuid(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=80), nullable=False),
    sa.Column('price_delta_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_modifiers_order_item_id'), 'order_item_modifiers', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_modifiers_order_item_id'), table_name='order_item_modifiers')
    op.drop_table('order_item_modifiers')
    op.drop_table('menu_item_modifier_groups')
    op.drop_index(op.f('ix_modifiers_modifier_group_id'), table_name='modifiers')
    op.drop_table('modifiers')
    op.drop_index(op.f('ix_modifier_groups_restaurant_id'), table_name='modifier_groups')
    op.drop_table('modifier_groups')
    # ### end Alembic commands ###
