"""add service charge to orders

Revision ID: de815686af5e
Revises: 69da4ff82cac
Create Date: 2026-06-27 12:13:28.282347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de815686af5e'
down_revision: Union[str, None] = '69da4ff82cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('service_charge_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('service_charge_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'service_charge_amount')
    op.drop_column('orders', 'service_charge_rate')
    # ### end Alembic commands ###
